"""add extra_data to page_sections

Revision ID: 044eb0c39d3d
Revises: 5801b6f571dd
Create Date: 2026-01-19 17:14:24.518102
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044eb0c39d3d'
down_revision = '5801b6f571dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_sections', sa.Column('extra_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_sections', 'extra_data')
    # ### end Alembic commands ###
