"""added parent

Revision ID: 0cdbbbf20e44
Revises: d4ee643f6627
Create Date: 2025-12-23 12:48:51.119993
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdbbbf20e44'
down_revision = 'd4ee643f6627'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colleges', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'colleges', 'colleges', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'colleges', type_='foreignkey')
    op.drop_column('colleges', 'parent_id')
    # ### end Alembic commands ###
