"""added sections

Revision ID: 16febab37616
Revises: 0cdbbbf20e44
Create Date: 2025-12-23 14:10:30.181055
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16febab37616'
down_revision = '0cdbbbf20e44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('section_subtitle', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_section_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shared_section_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('video_url', sa.String(length=1024), nullable=True),
    sa.Column('cta_text', sa.String(length=255), nullable=True),
    sa.Column('cta_link', sa.String(length=1024), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shared_section_id'], ['shared_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_shared_sections',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('shared_section_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_section_id'], ['shared_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id', 'shared_section_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_shared_sections')
    op.drop_table('shared_section_items')
    op.drop_table('shared_sections')
    # ### end Alembic commands ###
