"""add section_link to page_sections

Revision ID: 1a2b3c4d5e6f
Revises: 044eb0c39d3d
Create Date: 2026-01-21 00:00:00.000000
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = '044eb0c39d3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_sections', sa.Column('section_link', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_sections', 'section_link')
    # ### end Alembic commands ###
