"""add_page_inheritance_and_templates

Revision ID: 5801b6f571dd
Revises: 16febab37616
Create Date: 2026-01-08 17:47:49.030297
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5801b6f571dd'
down_revision = '16febab37616'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_sections', sa.Column('section_description', sa.Text(), nullable=True))
    op.add_column('page_sections', sa.Column('background_type', sa.String(length=50), nullable=True))
    op.add_column('page_sections', sa.Column('background_color', sa.String(length=20), nullable=True))
    op.add_column('page_sections', sa.Column('background_image', sa.String(length=1024), nullable=True))
    op.add_column('page_sections', sa.Column('background_gradient', sa.String(length=255), nullable=True))
    op.add_column('pages', sa.Column('template_type', sa.String(length=50), nullable=True))
    op.add_column('pages', sa.Column('parent_page_id', sa.Integer(), nullable=True))
    op.add_column('pages', sa.Column('is_inheritable', sa.Boolean(), nullable=False))
    op.create_index('ix_pages_college_active', 'pages', ['college_id', 'is_active'], unique=False)
    op.create_index('ix_pages_parent_id', 'pages', ['parent_page_id'], unique=False)
    op.create_foreign_key(None, 'pages', 'pages', ['parent_page_id'], ['id'], ondelete='SET NULL')
    op.add_column('seo_meta', sa.Column('focus_keyword', sa.String(length=255), nullable=True))
    op.add_column('seo_meta', sa.Column('readability_score', sa.String(length=50), nullable=True))
    op.add_column('seo_meta', sa.Column('seo_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seo_meta', 'seo_score')
    op.drop_column('seo_meta', 'readability_score')
    op.drop_column('seo_meta', 'focus_keyword')
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.drop_index('ix_pages_parent_id', table_name='pages')
    op.drop_index('ix_pages_college_active', table_name='pages')
    op.drop_column('pages', 'is_inheritable')
    op.drop_column('pages', 'parent_page_id')
    op.drop_column('pages', 'template_type')
    op.drop_column('page_sections', 'background_gradient')
    op.drop_column('page_sections', 'background_image')
    op.drop_column('page_sections', 'background_color')
    op.drop_column('page_sections', 'background_type')
    op.drop_column('page_sections', 'section_description')
    # ### end Alembic commands ###
